# **************************************************************************** #
#                                                           LE - /             #
#                                                               /              #
#    Makefile                                         .::    .:/ .      .::    #
#                                                  +:+:+   +:    +:  +:+:+     #
#    By: maegaspa <marvin@le-101.fr>                +:+   +:    +:    +:+      #
#                                                  #+#   #+    #+    #+#       #
#    Created: 2018/10/03 14:35:51 by maegaspa     #+#   ##    ##    #+#        #
#    Updated: 2018/10/03 17:21:33 by maegaspa    ###    #+. /#+    ###.fr      #
#                                                          /                   #
#                                                         /                    #
# **************************************************************************** #

NAME = ft_display_file

SOURCE = ft_putchar.c ft_putstr.c ft_putchar2.c ft_putstr2.c ft_display_file.c

HEADER = header.h

all :
	gcc -Wall -Wextra -Werror $(SOURCE) -o $(NAME)

clean :

fclean : clean
	rm -f $(NAME)

re : fclean all
